### ISSUE TITLE
日本語URLが保存出来ないのでリダイレクト設定が出来ない

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/vk-link-target-controller#16]

**Comment by dswebstudio** [comment]
#17　を修正した同時にこっちも修正されました。文字デコードの問題でした。

**Comment by dswebstudio** [comment]
このようなURL「http://k-kanna.com/日常＋/新年早々開き直り/」を入れても保存できるようになりました。

**Comment by kurudrive** [comment]
確認しました。ありがとうございます。
_|＼○_ﾋｬｯ ε=＼＿○ﾉ ﾎｰｳ!!
